#!/usr/bin/env python3
"""
Base Report Module - Base classes and utilities for report generation
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
from datetime import datetime
from gtasks_cli.models.task import Task
from gtasks_cli.utils.logger import setup_logger

logger = setup_logger(__name__)


class BaseReport(ABC):
    """Abstract base class for all reports."""
    
    def __init__(self, name: str, description: str):
        """
        Initialize the base report.
        
        Args:
            name: Name of the report
            description: Description of the report
        """
        self.name = name
        self.description = description
    
    @abstractmethod
    def generate(self, tasks: List[Task], **kwargs) -> Dict[str, Any]:
        """
        Generate the report data.
        
        Args:
            tasks: List of tasks to generate report from
            **kwargs: Additional parameters for report generation
            
        Returns:
            Dict containing report data
        """
        pass
    
    @abstractmethod
    def export(self, data: Dict[str, Any], format: str = 'txt', **kwargs) -> str:
        """
        Export the report in the specified format.
        
        Args:
            data: Report data generated by generate() method
            format: Export format (txt, csv, pdf)
            
        Returns:
            String representation of the exported report
        """
        pass


class ReportManager:
    """Manager for handling different types of reports."""
    
    def __init__(self):
        """Initialize the report manager."""
        self.reports = {}
    
    def register_report(self, report_id: str, report: BaseReport):
        """
        Register a new report type.
        
        Args:
            report_id: Unique identifier for the report
            report: Report instance
        """
        self.reports[report_id] = report
        logger.debug(f"Registered report: {report_id}")
    
    def get_report(self, report_id: str) -> Optional[BaseReport]:
        """
        Get a registered report by ID.
        
        Args:
            report_id: Report identifier
            
        Returns:
            Report instance or None if not found
        """
        return self.reports.get(report_id)
    
    def list_reports(self) -> Dict[str, Dict[str, str]]:
        """
        List all available reports.
        
        Returns:
            Dictionary of report information
        """
        report_list = {}
        for report_id, report in self.reports.items():
            report_list[report_id] = {
                'name': report.name,
                'description': report.description
            }
        return report_list
    
    def generate_report(self, report_id: str, tasks: List[Task], **kwargs) -> Optional[Dict[str, Any]]:
        """
        Generate a specific report.
        
        Args:
            report_id: Report identifier
            tasks: List of tasks to generate report from
            **kwargs: Additional parameters for report generation
            
        Returns:
            Report data or None if report not found
        """
        report = self.get_report(report_id)
        if not report:
            logger.error(f"Report '{report_id}' not found")
            return None
        
        try:
            logger.info(f"Generating report: {report.name}")
            return report.generate(tasks, **kwargs)
        except Exception as e:
            logger.error(f"Error generating report '{report_id}': {e}")
            return None
    
    def export_report(self, report_id: str, data: Dict[str, Any], format: str = 'txt', **kwargs) -> Optional[str]:
        """
        Export a report in the specified format.
        
        Args:
            report_id: Report identifier
            data: Report data to export
            format: Export format (txt, csv, pdf)
            
        Returns:
            Exported report string or None if report not found
        """
        report = self.get_report(report_id)
        if not report:
            logger.error(f"Report '{report_id}' not found")
            return None
        
        try:
            logger.info(f"Exporting report: {report.name} in {format} format")
            return report.export(data, format, **kwargs)
        except Exception as e:
            logger.error(f"Error exporting report '{report_id}': {e}")
            return None