#!/usr/bin/env python3
"""
Future Timeline Report - Tasks scheduled for future dates.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime, timedelta
from gtasks_cli.models.task import Task, TaskStatus, Priority
from gtasks_cli.reports.base_report import BaseReport
from gtasks_cli.utils.logger import setup_logger
import csv
import io

logger = setup_logger(__name__)


class FutureTimelineReport(BaseReport):
    """Report showing tasks scheduled for future dates."""
    
    def __init__(self):
        """Initialize the future timeline report."""
        super().__init__(
            name="Future Timeline Report",
            description="Tasks scheduled for future dates"
        )
    
    def generate(self, tasks: List[Task], **kwargs) -> Dict[str, Any]:
        """
        Generate the future timeline report.
        
        Args:
            tasks: List of tasks to generate report from
            **kwargs: Additional parameters (days_ahead)
            
        Returns:
            Dict containing report data
        """
        days_ahead = kwargs.get('days_ahead', 30)
        today = datetime.now().date()
        future_date = today + timedelta(days=days_ahead)
        
        # Filter future tasks (pending tasks with due date in the future)
        future_tasks = []
        for task in tasks:
            if (task.status == TaskStatus.PENDING and 
                task.due and 
                today <= task.due.date() <= future_date):
                future_tasks.append(task)
        
        # Sort by due date
        future_tasks.sort(key=lambda x: x.due)
        
        # Group by week
        weekly_tasks = {}
        for task in future_tasks:
            # Calculate week number from today
            days_until = (task.due.date() - today).days
            week_number = (days_until // 7) + 1
            week_key = f"Week {week_number}"
            
            if week_key not in weekly_tasks:
                weekly_tasks[week_key] = []
            weekly_tasks[week_key].append(task)
        
        # Group by priority
        high_priority = [task for task in future_tasks if task.priority == Priority.HIGH]
        medium_priority = [task for task in future_tasks if task.priority == Priority.MEDIUM]
        low_priority = [task for task in future_tasks if task.priority == Priority.LOW]
        
        report_data = {
            'report_name': self.name,
            'report_description': self.description,
            'period_start': today.isoformat(),
            'period_end': future_date.isoformat(),
            'days_ahead': days_ahead,
            'total_future_tasks': len(future_tasks),
            'high_priority': high_priority,
            'medium_priority': medium_priority,
            'low_priority': low_priority,
            'weekly_tasks': weekly_tasks,
            'generated_at': datetime.now().isoformat()
        }
        
        logger.debug(f"Generated future timeline report with {len(future_tasks)} future tasks")
        return report_data
    
    def export(self, data: Dict[str, Any], format: str = 'txt') -> str:
        """
        Export the future timeline report in the specified format.
        
        Args:
            data: Report data generated by generate() method
            format: Export format (txt, csv)
            
        Returns:
            String representation of the exported report
        """
        if format.lower() == 'csv':
            return self._export_csv(data)
        else:
            return self._export_text(data)
    
    def _export_text(self, data: Dict[str, Any]) -> str:
        """Export report as text."""
        output = []
        output.append("=" * 50)
        output.append(f"{data['report_name']}")
        output.append("=" * 50)
        output.append(f"Description: {data['report_description']}")
        output.append(f"Period: {data['period_start']} to {data['period_end']} ({data['days_ahead']} days ahead)")
        output.append(f"Generated at: {data['generated_at']}")
        output.append(f"")
        output.append(f"Summary:")
        output.append(f"  Total future tasks: {data['total_future_tasks']}")
        output.append(f"  High priority: {len(data['high_priority'])}")
        output.append(f"  Medium priority: {len(data['medium_priority'])}")
        output.append(f"  Low priority: {len(data['low_priority'])}")
        output.append(f"")
        
        # Weekly breakdown
        if data['weekly_tasks']:
            output.append(f"Future Tasks by Week:")
            for week, tasks in data['weekly_tasks'].items():
                output.append(f"  {week}: {len(tasks)} tasks")
                for i, task in enumerate(tasks, 1):
                    due_str = task.due.strftime("%Y-%m-%d") if task.due else "No due date"
                    priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                    output.append(f"    {i}. {task.title}")
                    output.append(f"       Due: {due_str} | Priority: {priority_str}")
                    if task.description:
                        desc = task.description[:50] + "..." if len(task.description) > 50 else task.description
                        output.append(f"       Description: {desc}")
                    if task.tags:
                        output.append(f"       Tags: {', '.join(task.tags)}")
                output.append(f"")
        
        return "\n".join(output)
    
    def _export_csv(self, data: Dict[str, Any]) -> str:
        """Export report as CSV."""
        output = io.StringIO()
        writer = csv.writer(output)
        
        # Header
        writer.writerow(['Report', data['report_name']])
        writer.writerow(['Description', data['report_description']])
        writer.writerow(['Period Start', data['period_start']])
        writer.writerow(['Period End', data['period_end']])
        writer.writerow(['Days Ahead', data['days_ahead']])
        writer.writerow(['Generated At', data['generated_at']])
        writer.writerow([])  # Empty row
        
        # Summary
        writer.writerow(['Summary'])
        writer.writerow(['Total Future Tasks', data['total_future_tasks']])
        writer.writerow(['High Priority', len(data['high_priority'])])
        writer.writerow(['Medium Priority', len(data['medium_priority'])])
        writer.writerow(['Low Priority', len(data['low_priority'])])
        writer.writerow([])  # Empty row
        
        # Weekly breakdown
        writer.writerow(['Weekly Breakdown'])
        writer.writerow(['Week', 'Task Count'])
        for week, tasks in data['weekly_tasks'].items():
            writer.writerow([week, len(tasks)])
        writer.writerow([])  # Empty row
        
        # All future tasks
        writer.writerow(['Future Tasks'])
        writer.writerow(['Week', 'Title', 'Due Date', 'Priority', 'Description', 'Tags'])
        
        for week, tasks in data['weekly_tasks'].items():
            for task in tasks:
                due_str = task.due.strftime("%Y-%m-%d") if task.due else ""
                priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                desc = task.description or ""
                tags_str = ", ".join(task.tags) if task.tags else ""
                writer.writerow([week, task.title, due_str, priority_str, desc, tags_str])
        
        return output.getvalue()