#!/usr/bin/env python3
"""
Overdue Tasks Report - Detailed list of tasks that are past their due dates.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from gtasks_cli.models.task import Task, TaskStatus, Priority
from gtasks_cli.reports.base_report import BaseReport
from gtasks_cli.utils.logger import setup_logger
import csv
import io

logger = setup_logger(__name__)


class OverdueTasksReport(BaseReport):
    """Report showing detailed list of tasks that are past their due dates."""
    
    def __init__(self):
        """Initialize the overdue tasks report."""
        super().__init__(
            name="Overdue Tasks Report",
            description="Detailed list of tasks that are past their due dates"
        )
    
    def generate(self, tasks: List[Task], **kwargs) -> Dict[str, Any]:
        """
        Generate the overdue tasks report.
        
        Args:
            tasks: List of tasks to generate report from
            **kwargs: Additional parameters
            
        Returns:
            Dict containing report data
        """
        # Filter overdue tasks (pending tasks with due date in the past)
        overdue_tasks = []
        today = datetime.now().date()
        
        for task in tasks:
            if (task.status == TaskStatus.PENDING and 
                task.due and 
                task.due.date() < today):
                # Calculate how many days overdue
                days_overdue = (today - task.due.date()).days
                # Create a copy of the task with the days_overdue attribute
                task_dict = task.model_dump()
                task_dict['days_overdue'] = days_overdue
                overdue_tasks.append((task, days_overdue))
        
        # Sort by how overdue they are (most overdue first)
        overdue_tasks.sort(key=lambda x: x[1], reverse=True)
        
        # Extract just the tasks for further processing
        overdue_task_list = [task for task, _ in overdue_tasks]
        
        # Group by how overdue
        very_overdue = [(task, days) for task, days in overdue_tasks if days >= 30]  # 30+ days
        moderately_overdue = [(task, days) for task, days in overdue_tasks if 7 <= days < 30]  # 7-29 days
        recently_overdue = [(task, days) for task, days in overdue_tasks if days < 7]  # < 7 days
        
        report_data = {
            'report_name': self.name,
            'report_description': self.description,
            'total_overdue': len(overdue_tasks),
            'very_overdue': [task for task, _ in very_overdue],  # 30+ days
            'moderately_overdue': [task for task, _ in moderately_overdue],  # 7-29 days
            'recently_overdue': [task for task, _ in recently_overdue],  # < 7 days
            'generated_at': datetime.now().isoformat(),
            '_overdue_details': {
                'very_overdue': very_overdue,
                'moderately_overdue': moderately_overdue,
                'recently_overdue': recently_overdue
            }
        }
        
        logger.debug(f"Generated overdue tasks report with {len(overdue_tasks)} overdue tasks")
        return report_data
    
    def export(self, data: Dict[str, Any], format: str = 'txt') -> str:
        """
        Export the overdue tasks report in the specified format.
        
        Args:
            data: Report data generated by generate() method
            format: Export format (txt, csv)
            
        Returns:
            String representation of the exported report
        """
        if format.lower() == 'csv':
            return self._export_csv(data)
        else:
            return self._export_text(data)
    
    def _export_text(self, data: Dict[str, Any]) -> str:
        """Export report as text."""
        output = []
        output.append("=" * 50)
        output.append(f"{data['report_name']}")
        output.append("=" * 50)
        output.append(f"Description: {data['report_description']}")
        output.append(f"Generated at: {data['generated_at']}")
        output.append(f"")
        output.append(f"Summary:")
        output.append(f"  Total overdue tasks: {data['total_overdue']}")
        output.append(f"  Very overdue (30+ days): {len(data['very_overdue'])}")
        output.append(f"  Moderately overdue (7-29 days): {len(data['moderately_overdue'])}")
        output.append(f"  Recently overdue (< 7 days): {len(data['recently_overdue'])}")
        output.append(f"")
        
        # Get the overdue details
        overdue_details = data.get('_overdue_details', {})
        very_overdue_details = overdue_details.get('very_overdue', [])
        moderately_overdue_details = overdue_details.get('moderately_overdue', [])
        recently_overdue_details = overdue_details.get('recently_overdue', [])
        
        if very_overdue_details:
            output.append(f"Very Overdue Tasks (30+ days):")
            for i, (task, days_overdue) in enumerate(very_overdue_details, 1):
                due_str = task.due.strftime("%Y-%m-%d") if task.due else "No due date"
                priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                output.append(f"  {i}. {task.title}")
                output.append(f"     Due: {due_str} ({days_overdue} days overdue) | Priority: {priority_str}")
                if task.description:
                    # Truncate description for readability
                    desc = task.description[:50] + "..." if len(task.description) > 50 else task.description
                    output.append(f"     Description: {desc}")
                if task.tags:
                    output.append(f"     Tags: {', '.join(task.tags)}")
            output.append(f"")
        
        if moderately_overdue_details:
            output.append(f"Moderately Overdue Tasks (7-29 days):")
            for i, (task, days_overdue) in enumerate(moderately_overdue_details, 1):
                due_str = task.due.strftime("%Y-%m-%d") if task.due else "No due date"
                priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                output.append(f"  {i}. {task.title}")
                output.append(f"     Due: {due_str} ({days_overdue} days overdue) | Priority: {priority_str}")
                if task.description:
                    desc = task.description[:50] + "..." if len(task.description) > 50 else task.description
                    output.append(f"     Description: {desc}")
                if task.tags:
                    output.append(f"     Tags: {', '.join(task.tags)}")
            output.append(f"")
        
        if recently_overdue_details:
            output.append(f"Recently Overdue Tasks (< 7 days):")
            for i, (task, days_overdue) in enumerate(recently_overdue_details, 1):
                due_str = task.due.strftime("%Y-%m-%d") if task.due else "No due date"
                priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                output.append(f"  {i}. {task.title}")
                output.append(f"     Due: {due_str} ({days_overdue} days overdue) | Priority: {priority_str}")
                if task.description:
                    desc = task.description[:50] + "..." if len(task.description) > 50 else task.description
                    output.append(f"     Description: {desc}")
                if task.tags:
                    output.append(f"     Tags: {', '.join(task.tags)}")
        
        return "\n".join(output)
    
    def _export_csv(self, data: Dict[str, Any]) -> str:
        """Export report as CSV."""
        output = io.StringIO()
        writer = csv.writer(output)
        
        # Header
        writer.writerow(['Report', data['report_name']])
        writer.writerow(['Description', data['report_description']])
        writer.writerow(['Generated At', data['generated_at']])
        writer.writerow([])  # Empty row
        
        # Summary
        writer.writerow(['Summary'])
        writer.writerow(['Total Overdue Tasks', data['total_overdue']])
        writer.writerow(['Very Overdue (30+ days)', len(data['very_overdue'])])
        writer.writerow(['Moderately Overdue (7-29 days)', len(data['moderately_overdue'])])
        writer.writerow(['Recently Overdue (< 7 days)', len(data['recently_overdue'])])
        writer.writerow([])  # Empty row
        
        # Get the overdue details
        overdue_details = data.get('_overdue_details', {})
        very_overdue_details = overdue_details.get('very_overdue', [])
        moderately_overdue_details = overdue_details.get('moderately_overdue', [])
        recently_overdue_details = overdue_details.get('recently_overdue', [])
        
        # All overdue tasks
        writer.writerow(['Overdue Tasks'])
        writer.writerow(['Category', 'Title', 'Due Date', 'Days Overdue', 'Priority', 'Description', 'Tags'])
        
        # Very overdue tasks
        for task, days_overdue in very_overdue_details:
            due_str = task.due.strftime("%Y-%m-%d") if task.due else ""
            priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
            desc = task.description or ""
            tags_str = ", ".join(task.tags) if task.tags else ""
            writer.writerow(['Very Overdue', task.title, due_str, days_overdue, priority_str, desc, tags_str])
        
        # Moderately overdue tasks
        for task, days_overdue in moderately_overdue_details:
            due_str = task.due.strftime("%Y-%m-%d") if task.due else ""
            priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
            desc = task.description or ""
            tags_str = ", ".join(task.tags) if task.tags else ""
            writer.writerow(['Moderately Overdue', task.title, due_str, days_overdue, priority_str, desc, tags_str])
        
        # Recently overdue tasks
        for task, days_overdue in recently_overdue_details:
            due_str = task.due.strftime("%Y-%m-%d") if task.due else ""
            priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
            desc = task.description or ""
            tags_str = ", ".join(task.tags) if task.tags else ""
            writer.writerow(['Recently Overdue', task.title, due_str, days_overdue, priority_str, desc, tags_str])
        
        return output.getvalue()