#!/usr/bin/env python3
"""
Pending Tasks Report - List of all pending tasks with their due dates.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from gtasks_cli.models.task import Task, TaskStatus, Priority
from gtasks_cli.reports.base_report import BaseReport
from gtasks_cli.utils.logger import setup_logger
import csv
import io

logger = setup_logger(__name__)


class PendingTasksReport(BaseReport):
    """Report showing list of all pending tasks with their due dates."""
    
    def __init__(self):
        """Initialize the pending tasks report."""
        super().__init__(
            name="Pending Tasks Report",
            description="List of all pending tasks with their due dates"
        )
    
    def generate(self, tasks: List[Task], **kwargs) -> Dict[str, Any]:
        """
        Generate the pending tasks report.
        
        Args:
            tasks: List of tasks to generate report from
            **kwargs: Additional parameters
            
        Returns:
            Dict containing report data
        """
        # Filter pending tasks
        pending_tasks = [task for task in tasks if task.status == TaskStatus.PENDING]
        
        # Sort by due date (if available) or created date
        pending_tasks.sort(key=lambda x: (
            x.due.replace(tzinfo=None) if x.due and hasattr(x.due, 'tzinfo') and x.due.tzinfo is not None else x.due or 
            x.created_at.replace(tzinfo=None) if x.created_at and hasattr(x.created_at, 'tzinfo') and x.created_at.tzinfo is not None else x.created_at or 
            datetime.max))
        
        # Categorize by due date status
        overdue = []
        due_soon = []  # Within 7 days
        future = []
        no_due_date = []
        
        today = datetime.now().date()
        
        for task in pending_tasks:
            if task.due:
                # Make sure due date is timezone-naive for comparison
                due_date_obj = task.due
                if hasattr(due_date_obj, 'tzinfo') and due_date_obj.tzinfo is not None:
                    due_date_obj = due_date_obj.replace(tzinfo=None)
                
                due_date = due_date_obj.date()
                if due_date < today:
                    overdue.append(task)
                elif (due_date - today).days <= 7:
                    due_soon.append(task)
                else:
                    future.append(task)
            else:
                no_due_date.append(task)
        
        report_data = {
            'report_name': self.name,
            'report_description': self.description,
            'total_pending': len(pending_tasks),
            'overdue': overdue,
            'due_soon': due_soon,
            'future': future,
            'no_due_date': no_due_date,
            'generated_at': datetime.now().isoformat()
        }
        
        logger.debug(f"Generated pending tasks report with {len(pending_tasks)} pending tasks")
        return report_data
    
    def export(self, data: Dict[str, Any], format: str = 'txt') -> str:
        """
        Export the pending tasks report in the specified format.
        
        Args:
            data: Report data generated by generate() method
            format: Export format (txt, csv)
            
        Returns:
            String representation of the exported report
        """
        if format.lower() == 'csv':
            return self._export_csv(data)
        else:
            return self._export_text(data)
    
    def _export_text(self, data: Dict[str, Any]) -> str:
        """Export report as text."""
        output = []
        output.append("=" * 50)
        output.append(f"{data['report_name']}")
        output.append("=" * 50)
        output.append(f"Description: {data['report_description']}")
        output.append(f"Generated at: {data['generated_at']}")
        output.append(f"")
        output.append(f"Summary:")
        output.append(f"  Total pending tasks: {data['total_pending']}")
        output.append(f"  Overdue: {len(data['overdue'])}")
        output.append(f"  Due soon (within 7 days): {len(data['due_soon'])}")
        output.append(f"  Future due dates: {len(data['future'])}")
        output.append(f"  No due date: {len(data['no_due_date'])}")
        output.append(f"")
        
        if data['overdue']:
            output.append(f"Overdue Tasks:")
            for i, task in enumerate(data['overdue'], 1):
                due_str = task.due.strftime("%Y-%m-%d") if task.due else "No due date"
                priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                output.append(f"  {i}. {task.title}")
                output.append(f"     Due: {due_str} | Priority: {priority_str}")
                if task.description:
                    # Truncate description for readability
                    desc = task.description[:50] + "..." if len(task.description) > 50 else task.description
                    output.append(f"     Description: {desc}")
            output.append(f"")
        
        if data['due_soon']:
            output.append(f"Due Soon Tasks:")
            for i, task in enumerate(data['due_soon'], 1):
                due_str = task.due.strftime("%Y-%m-%d") if task.due else "No due date"
                priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                output.append(f"  {i}. {task.title}")
                output.append(f"     Due: {due_str} | Priority: {priority_str}")
                if task.description:
                    desc = task.description[:50] + "..." if len(task.description) > 50 else task.description
                    output.append(f"     Description: {desc}")
            output.append(f"")
        
        if data['future']:
            output.append(f"Future Tasks:")
            for i, task in enumerate(data['future'], 1):
                due_str = task.due.strftime("%Y-%m-%d") if task.due else "No due date"
                priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                output.append(f"  {i}. {task.title}")
                output.append(f"     Due: {due_str} | Priority: {priority_str}")
                if task.description:
                    desc = task.description[:50] + "..." if len(task.description) > 50 else task.description
                    output.append(f"     Description: {desc}")
            output.append(f"")
        
        if data['no_due_date']:
            output.append(f"Tasks with No Due Date:")
            for i, task in enumerate(data['no_due_date'], 1):
                priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
                output.append(f"  {i}. {task.title}")
                output.append(f"     Priority: {priority_str}")
                if task.description:
                    desc = task.description[:50] + "..." if len(task.description) > 50 else task.description
                    output.append(f"     Description: {desc}")
        
        return "\n".join(output)
    
    def _export_csv(self, data: Dict[str, Any]) -> str:
        """Export report as CSV."""
        output = io.StringIO()
        writer = csv.writer(output)
        
        # Header
        writer.writerow(['Report', data['report_name']])
        writer.writerow(['Description', data['report_description']])
        writer.writerow(['Generated At', data['generated_at']])
        writer.writerow([])  # Empty row
        
        # Summary
        writer.writerow(['Summary'])
        writer.writerow(['Total Pending Tasks', data['total_pending']])
        writer.writerow(['Overdue', len(data['overdue'])])
        writer.writerow(['Due Soon', len(data['due_soon'])])
        writer.writerow(['Future', len(data['future'])])
        writer.writerow(['No Due Date', len(data['no_due_date'])])
        writer.writerow([])  # Empty row
        
        # All pending tasks
        writer.writerow(['Pending Tasks'])
        writer.writerow(['Category', 'Title', 'Due Date', 'Priority', 'Description'])
        
        # Overdue tasks
        for task in data['overdue']:
            due_str = task.due.strftime("%Y-%m-%d") if task.due else ""
            priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
            desc = task.description or ""
            writer.writerow(['Overdue', task.title, due_str, priority_str, desc])
        
        # Due soon tasks
        for task in data['due_soon']:
            due_str = task.due.strftime("%Y-%m-%d") if task.due else ""
            priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
            desc = task.description or ""
            writer.writerow(['Due Soon', task.title, due_str, priority_str, desc])
        
        # Future tasks
        for task in data['future']:
            due_str = task.due.strftime("%Y-%m-%d") if task.due else ""
            priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
            desc = task.description or ""
            writer.writerow(['Future', task.title, due_str, priority_str, desc])
        
        # No due date tasks
        for task in data['no_due_date']:
            priority_str = task.priority if isinstance(task.priority, str) else task.priority.value
            desc = task.description or ""
            writer.writerow(['No Due Date', task.title, '', priority_str, desc])
        
        return output.getvalue()