#!/usr/bin/env python3
"""
Task Distribution Report - Analysis of tasks by category, priority, or tags.
"""

from typing import List, Dict, Any, Optional
from collections import Counter
from datetime import datetime
from gtasks_cli.models.task import Task, TaskStatus, Priority
from gtasks_cli.reports.base_report import BaseReport
from gtasks_cli.utils.logger import setup_logger
import csv
import io

logger = setup_logger(__name__)


class TaskDistributionReport(BaseReport):
    """Report showing analysis of tasks by category, priority, or tags."""
    
    def __init__(self):
        """Initialize the task distribution report."""
        super().__init__(
            name="Task Distribution Report",
            description="Analysis of tasks by category, priority, or tags"
        )
    
    def generate(self, tasks: List[Task], **kwargs) -> Dict[str, Any]:
        """
        Generate the task distribution report.
        
        Args:
            tasks: List of tasks to generate report from
            **kwargs: Additional parameters
            
        Returns:
            Dict containing report data
        """
        # Distribution by status
        status_counter = Counter()
        for task in tasks:
            if task.status is None:
                status_counter['None'] += 1
            elif isinstance(task.status, str):
                status_counter[task.status] += 1
            else:
                # Handle case where status might be an enum
                status_counter[getattr(task.status, 'value', str(task.status))] += 1
        
        # Distribution by priority
        priority_counter = Counter()
        for task in tasks:
            if task.priority is None:
                priority_counter['None'] += 1
            elif isinstance(task.priority, str):
                priority_counter[task.priority] += 1
            else:
                # Handle case where priority might be an enum
                priority_counter[getattr(task.priority, 'value', str(task.priority))] += 1
        
        # Distribution by tags
        tag_counter = Counter()
        tagged_tasks = 0
        for task in tasks:
            if task.tags:
                tagged_tasks += 1
                for tag in task.tags:
                    tag_counter[tag] += 1
        
        # Distribution by projects (if available)
        project_counter = Counter()
        for task in tasks:
            if task.project:
                project_counter[task.project] += 1
        
        # Calculate percentages
        total_tasks = len(tasks)
        
        status_percentages = {
            status: (count / total_tasks * 100) if total_tasks > 0 else 0
            for status, count in status_counter.items()
        }
        
        priority_percentages = {
            priority: (count / total_tasks * 100) if total_tasks > 0 else 0
            for priority, count in priority_counter.items()
        }
        
        tag_percentages = {
            tag: (count / total_tasks * 100) if total_tasks > 0 else 0
            for tag, count in tag_counter.items()
        }
        
        project_percentages = {
            project: (count / total_tasks * 100) if total_tasks > 0 else 0
            for project, count in project_counter.items()
        }
        
        # Top tags (top 10)
        top_tags = tag_counter.most_common(10)
        
        # Top projects (top 10)
        top_projects = project_counter.most_common(10)
        
        report_data = {
            'report_name': self.name,
            'report_description': self.description,
            'total_tasks': total_tasks,
            'status_distribution': dict(status_counter),
            'status_percentages': status_percentages,
            'priority_distribution': dict(priority_counter),
            'priority_percentages': priority_percentages,
            'tag_distribution': dict(tag_counter),
            'tag_percentages': tag_percentages,
            'project_distribution': dict(project_counter),
            'project_percentages': project_percentages,
            'top_tags': top_tags,
            'top_projects': top_projects,
            'tagged_tasks': tagged_tasks,
            'tagged_tasks_percentage': (tagged_tasks / total_tasks * 100) if total_tasks > 0 else 0,
            'generated_at': datetime.now().isoformat()
        }
        
        logger.debug(f"Generated task distribution report for {total_tasks} tasks")
        return report_data
    
    def export(self, data: Dict[str, Any], format: str = 'txt') -> str:
        """
        Export the task distribution report in the specified format.
        
        Args:
            data: Report data generated by generate() method
            format: Export format (txt, csv)
            
        Returns:
            String representation of the exported report
        """
        if format.lower() == 'csv':
            return self._export_csv(data)
        else:
            return self._export_text(data)
    
    def _export_text(self, data: Dict[str, Any]) -> str:
        """Export report as text."""
        output = []
        output.append("=" * 50)
        output.append(f"{data['report_name']}")
        output.append("=" * 50)
        output.append(f"Description: {data['report_description']}")
        output.append(f"Generated at: {data['generated_at']}")
        output.append(f"")
        output.append(f"Summary:")
        output.append(f"  Total tasks: {data['total_tasks']}")
        output.append(f"  Tagged tasks: {data['tagged_tasks']} ({data['tagged_tasks_percentage']:.1f}%)")
        output.append(f"")
        
        # Status distribution
        output.append(f"Status Distribution:")
        for status, count in sorted(data['status_distribution'].items()):
            percentage = data['status_percentages'][status]
            output.append(f"  {status}: {count} ({percentage:.1f}%)")
        output.append(f"")
        
        # Priority distribution
        output.append(f"Priority Distribution:")
        
        # Define priority order for sorting (None is treated as 'Not Set' or default)
        priority_order = {
            'High': 1,
            'Medium': 2,
            'Low': 3,
            'None': 4
        }
        
        # Sort priorities by custom order, handling missing keys
        for priority, count in sorted(
            data['priority_distribution'].items(),
            key=lambda x: priority_order.get(x[0], 5)  # Default for unexpected values
        ):
            percentage = data['priority_percentages'][priority]
            output.append(f"  {priority}: {count} ({percentage:.1f}%)")
        output.append(f"")
        
        # Top tags
        if data['top_tags']:
            output.append(f"Top Tags:")
            for i, (tag, count) in enumerate(data['top_tags'], 1):
                percentage = data['tag_percentages'][tag]
                output.append(f"  {i}. {tag}: {count} ({percentage:.1f}%)")
            output.append(f"")
        
        # Top projects
        if data['top_projects']:
            output.append(f"Top Projects:")
            for i, (project, count) in enumerate(data['top_projects'], 1):
                percentage = data['project_percentages'][project]
                output.append(f"  {i}. {project}: {count} ({percentage:.1f}%)")
        
        return "\n".join(output)
    
    def _export_csv(self, data: Dict[str, Any]) -> str:
        """Export report as CSV."""
        output = io.StringIO()
        writer = csv.writer(output)
        
        # Header
        writer.writerow(['Report', data['report_name']])
        writer.writerow(['Description', data['report_description']])
        writer.writerow(['Generated At', data['generated_at']])
        writer.writerow([])  # Empty row
        
        # Summary
        writer.writerow(['Summary'])
        writer.writerow(['Total Tasks', data['total_tasks']])
        writer.writerow(['Tagged Tasks', data['tagged_tasks']])
        writer.writerow(['Tagged Tasks %', f"{data['tagged_tasks_percentage']:.1f}"])
        writer.writerow([])  # Empty row
        
        # Status distribution
        writer.writerow(['Status Distribution'])
        writer.writerow(['Status', 'Count', 'Percentage'])
        for status, count in sorted(data['status_distribution'].items()):
            percentage = data['status_percentages'][status]
            writer.writerow([status, count, f"{percentage:.1f}"])
        writer.writerow([])  # Empty row
        
        # Priority distribution
        writer.writerow(['Priority Distribution'])
        writer.writerow(['Priority', 'Count', 'Percentage'])
        
        # Define priority order for sorting (None is treated as 'Not Set' or default)
        priority_order = {
            'High': 1,
            'Medium': 2,
            'Low': 3,
            'None': 4
        }
        
        # Sort priorities by custom order, handling missing keys
        for priority, count in sorted(
            data['priority_distribution'].items(),
            key=lambda x: priority_order.get(x[0], 5)  # Default for unexpected values
        ):
            percentage = data['priority_percentages'][priority]
            writer.writerow([priority, count, f"{percentage:.1f}"])
        writer.writerow([])  # Empty row
        
        # Tag distribution
        writer.writerow(['Top Tags'])
        writer.writerow(['Tag', 'Count', 'Percentage'])
        for tag, count in data['top_tags']:
            percentage = data['tag_percentages'][tag]
            writer.writerow([tag, count, f"{percentage:.1f}"])
        writer.writerow([])  # Empty row
        
        # Project distribution
        writer.writerow(['Top Projects'])
        writer.writerow(['Project', 'Count', 'Percentage'])
        for project, count in data['top_projects']:
            percentage = data['project_percentages'][project]
            writer.writerow([project, count, f"{percentage:.1f}"])
        
        return output.getvalue()